function step5_trading_strategy_backtest()
%STEP5_TRADING_STRATEGY_BACKTEST
% Step 5 - Trading Strategy Design & Portfolio Backtesting
%
% Uses factor_dataset.csv generated by Step 3.
%
% Model selected in Step 4:
%   AR(5)
%
% Important:
%   - Model selection is based on validation RMSE.
%   - Trading threshold is optimized using validation data only.
%   - Final AR(5) is refitted using train + validation data.
%   - Test period is kept separate for final evaluation.
%   - Signals at day t are applied to the return from t -> t+1.
%   - Transaction costs are included.

clc;
close all;

fprintf('\n============================================================\n');
fprintf(' [STEP 5] TRADING STRATEGY DESIGN & PORTFOLIO BACKTESTING\n');
fprintf('============================================================\n\n');

%% ============================================================
% 1. PATH SETUP
% ============================================================

thisFile = mfilename('fullpath');

if isempty(thisFile)
    srcDir = pwd;
else
    srcDir = fileparts(thisFile);
end

projectDir = fileparts(srcDir);

dataDir    = fullfile(projectDir, 'data', 'processed');
modelsDir  = fullfile(projectDir, 'results', 'models');
tablesDir  = fullfile(projectDir, 'results', 'tables');
figuresDir = fullfile(projectDir, 'results', 'figures');

if ~exist(modelsDir, 'dir')
    mkdir(modelsDir);
end

if ~exist(tablesDir, 'dir')
    mkdir(tablesDir);
end

if ~exist(figuresDir, 'dir')
    mkdir(figuresDir);
end

addpath(srcDir);
addpath(fullfile(srcDir, 'utils'));

%% ============================================================
% 2. LOAD FACTOR DATASET
% ============================================================

fprintf('-> Loading factor dataset...\n');

factorFile = fullfile(dataDir, 'factor_dataset.csv');

if ~isfile(factorFile)
    error('step5:missingFactorDataset', ...
        ['factor_dataset.csv not found.\n' ...
         'Expected location:\n%s\n' ...
         'Please run Step 3 first.'], ...
         factorFile);
end

fprintf('   File: %s\n', factorFile);

T = readtable(factorFile);

fprintf('   Rows loaded: %d\n', height(T));
fprintf('   Columns    : %d\n', width(T));

%% ============================================================
% 3. DISPLAY AVAILABLE VARIABLES
% ============================================================

fprintf('\n------------------------------------------------------------\n');
fprintf(' [DATASET VARIABLES]\n');
fprintf('------------------------------------------------------------\n');

variableNames = T.Properties.VariableNames;

for i = 1:numel(variableNames)
    fprintf('   %s\n', variableNames{i});
end

%% ============================================================
% 4. FIND IMPORTANT COLUMNS
% ============================================================

dateColumn = findColumn(T, { ...
    'Date', ...
    'date', ...
    'time', ...
    'OpenTime', ...
    'Open_time'});

priceColumn = findColumn(T, { ...
    'Close', ...
    'close', ...
    'BTC_Close', ...
    'Price', ...
    'price'});

targetColumn = findColumn(T, { ...
    'TargetReturn1D', ...
    'Target_Return_1D', ...
    'TargetReturn', ...
    'target_return', ...
    'Target'});

sentimentColumn = findColumn(T, { ...
    'Sentiment', ...
    'sentiment', ...
    'SentimentScore', ...
    'sentiment_score'});

if isempty(dateColumn)
    error('step5:dateColumnMissing', ...
        'Could not identify the date column.');
end

if isempty(priceColumn)
    error('step5:priceColumnMissing', ...
        'Could not identify the BTC closing price column.');
end

if isempty(targetColumn)
    error('step5:targetColumnMissing', ...
        'Could not identify the target return column.');
end

if isempty(sentimentColumn)
    warning('Sentiment column not found. Sentiment-filtered strategy will be disabled.');
end

fprintf('\nIdentified columns:\n');
fprintf('   Date      : %s\n', dateColumn);
fprintf('   Price     : %s\n', priceColumn);
fprintf('   Target    : %s\n', targetColumn);

if ~isempty(sentimentColumn)
    fprintf('   Sentiment : %s\n', sentimentColumn);
end

%% ============================================================
% 5. EXTRACT DATA
% ============================================================

dates = convertToDatetime(T.(dateColumn));

prices = convertToNumeric(T.(priceColumn));

target = convertToNumeric(T.(targetColumn));

if ~isempty(sentimentColumn)
    sentiment = convertToNumeric(T.(sentimentColumn));
else
    sentiment = NaN(height(T),1);
end

%% ============================================================
% 6. REMOVE INVALID ROWS
% ============================================================

valid = ...
    ~isnat(dates) & ...
    isfinite(prices) & ...
    prices > 0 & ...
    isfinite(target);

if ~isempty(sentimentColumn)
    % Sentiment is not required for the main model strategy.
    % Therefore do not remove rows just because sentiment is NaN.
end

dates     = dates(valid);
prices    = prices(valid);
target    = target(valid);
sentiment = sentiment(valid);

fprintf('\nValid observations: %d\n', numel(target));

if numel(target) < 100
    error('step5:insufficientData', ...
        'Too few valid observations for backtesting.');
end

%% ============================================================
% 7. DATA SPLIT
% ============================================================

n = numel(target);

trainEnd = floor(0.70 * n);
valEnd   = floor(0.85 * n);

trainIdx = (1:trainEnd)';
valIdx   = (trainEnd+1:valEnd)';
testIdx  = (valEnd+1:n)';

fprintf('\n------------------------------------------------------------\n');
fprintf(' [DATA SPLIT]\n');
fprintf('------------------------------------------------------------\n');

fprintf('Total observations : %d\n', n);
fprintf('Training           : %d\n', numel(trainIdx));
fprintf('Validation         : %d\n', numel(valIdx));
fprintf('Test               : %d\n', numel(testIdx));

fprintf('\nTraining dates:\n');
fprintf('  %s -> %s\n', ...
    datestr(dates(trainIdx(1)), 'yyyy-mm-dd'), ...
    datestr(dates(trainIdx(end)), 'yyyy-mm-dd'));

fprintf('Validation dates:\n');
fprintf('  %s -> %s\n', ...
    datestr(dates(valIdx(1)), 'yyyy-mm-dd'), ...
    datestr(dates(valIdx(end)), 'yyyy-mm-dd'));

fprintf('Test dates:\n');
fprintf('  %s -> %s\n', ...
    datestr(dates(testIdx(1)), 'yyyy-mm-dd'), ...
    datestr(dates(testIdx(end)), 'yyyy-mm-dd'));

fprintf('------------------------------------------------------------\n');

%% ============================================================
% 8. TRAIN AR(5) ON TRAINING DATA
% ============================================================

fprintf('\n============================================================\n');
fprintf(' AR(5) VALIDATION MODEL\n');
fprintf('============================================================\n');

lagOrder = 5;

yTrain = target(trainIdx);
yVal   = target(valIdx);
yTest  = target(testIdx);

fprintf('-> Training AR(%d) using training data only...\n', lagOrder);

arTrain = fitARModel(yTrain, lagOrder);

%% ============================================================
% 9. VALIDATION PREDICTIONS
% ============================================================

fprintf('-> Generating validation predictions...\n');

historyVal = [yTrain(end-lagOrder+1:end); yVal];

valPred = zeros(numel(yVal),1);

for t = 1:numel(yVal)

    currentIndex = lagOrder + t;

    lagValues = historyVal( ...
        currentIndex-lagOrder:currentIndex-1);

    lagValues = flipud(lagValues);

    X = [1; lagValues];

    valPred(t) = X' * arTrain.beta;
end

%% ============================================================
% 10. VALIDATION METRICS
% ============================================================

valRMSE = sqrt(mean((yVal-valPred).^2));
valMAE  = mean(abs(yVal-valPred));

ssRes = sum((yVal-valPred).^2);
ssTot = sum((yVal-mean(yVal)).^2);

if ssTot > eps
    valR2 = 1 - ssRes/ssTot;
else
    valR2 = NaN;
end

fprintf('\nValidation RMSE: %.6f\n', valRMSE);
fprintf('Validation MAE : %.6f\n', valMAE);
fprintf('Validation R2  : %.4f\n', valR2);

%% ============================================================
% 11. VALIDATION THRESHOLD SEARCH
% ============================================================

fprintf('\n============================================================\n');
fprintf(' VALIDATION TRADING THRESHOLD SEARCH\n');
fprintf('============================================================\n');

fprintf('Threshold optimized using VALIDATION data only.\n');

candidateThresholds = 0:0.0005:0.015;

bestThreshold = candidateThresholds(1);
bestValSharpe = -Inf;

priceVal = prices(valIdx);

for i = 1:numel(candidateThresholds)

    threshold = candidateThresholds(i);

    valSignals = generateSignals( ...
        valPred, ...
        threshold, ...
        threshold);

    btVal = runBacktest( ...
        priceVal, ...
        valSignals, ...
        10000, ...
        0.001, ...
        true);

    if isfinite(btVal.sharpeRatio)

        if btVal.sharpeRatio > bestValSharpe

            bestValSharpe = btVal.sharpeRatio;
            bestThreshold = threshold;
        end
    end
end

fprintf('\nBest validation threshold: %.4f\n', bestThreshold);
fprintf('Best validation Sharpe   : %.4f\n', bestValSharpe);

%% ============================================================
% 12. FINAL MODEL: TRAIN + VALIDATION
% ============================================================

fprintf('\n============================================================\n');
fprintf(' FINAL AR(5) MODEL\n');
fprintf('============================================================\n');

developmentY = [yTrain; yVal];

fprintf('-> Refitting AR(5) using training + validation data...\n');
fprintf('   Observations: %d\n', numel(developmentY));

arFinal = fitARModel(developmentY, lagOrder);

%% ============================================================
% 13. TEST PREDICTIONS
% ============================================================

fprintf('-> Generating TEST predictions...\n');

historyTest = [developmentY(end-lagOrder+1:end); yTest];

testPred = zeros(numel(yTest),1);

for t = 1:numel(yTest)

    currentIndex = lagOrder + t;

    lagValues = historyTest( ...
        currentIndex-lagOrder:currentIndex-1);

    lagValues = flipud(lagValues);

    X = [1; lagValues];

    testPred(t) = X' * arFinal.beta;
end

%% ============================================================
% 14. TEST MODEL METRICS
% ============================================================

testRMSE = sqrt(mean((yTest-testPred).^2));
testMAE  = mean(abs(yTest-testPred));

ssRes = sum((yTest-testPred).^2);
ssTot = sum((yTest-mean(yTest)).^2);

if ssTot > eps
    testR2 = 1 - ssRes/ssTot;
else
    testR2 = NaN;
end

fprintf('\n------------------------------------------------------------\n');
fprintf(' FINAL TEST MODEL PERFORMANCE\n');
fprintf('------------------------------------------------------------\n');

fprintf('Test RMSE: %.6f\n', testRMSE);
fprintf('Test MAE : %.6f\n', testMAE);
fprintf('Test R2  : %.4f\n', testR2);

%% ============================================================
% 15. GENERATE AR(5) TEST SIGNALS
% ============================================================

fprintf('\n============================================================\n');
fprintf(' AR(5) TRADING SIGNALS\n');
fprintf('============================================================\n');

arSignals = generateSignals( ...
    testPred, ...
    bestThreshold, ...
    bestThreshold);

fprintf('BUY  signals: %d\n', sum(arSignals=="BUY"));
fprintf('SELL signals: %d\n', sum(arSignals=="SELL"));
fprintf('HOLD signals: %d\n', sum(arSignals=="HOLD"));

%% ============================================================
% 16. SENTIMENT FILTER
% ============================================================

fprintf('\n============================================================\n');
fprintf(' SENTIMENT FILTER\n');
fprintf('============================================================\n');

sentimentAvailable = ~isempty(sentimentColumn);

if sentimentAvailable

    developmentSentiment = sentiment( ...
        [trainIdx; valIdx]);

    developmentSentiment = ...
        developmentSentiment(isfinite(developmentSentiment));

    if isempty(developmentSentiment)

        sentimentAvailable = false;

    else

        sentimentMean = mean(developmentSentiment);

        fprintf('Development sentiment mean: %.6f\n', ...
            sentimentMean);

        sentimentTest = sentiment(testIdx);

        filteredSignals = arSignals;

        buyMask = arSignals == "BUY";

        weakSentiment = ...
            isfinite(sentimentTest) & ...
            sentimentTest < sentimentMean;

        filteredSignals( ...
            buyMask & weakSentiment) = "HOLD";

        fprintf('Original BUY signals : %d\n', ...
            sum(arSignals=="BUY"));

        fprintf('Filtered BUY signals : %d\n', ...
            sum(filteredSignals=="BUY"));

        fprintf('Removed BUY signals  : %d\n', ...
            sum(arSignals=="BUY") - ...
            sum(filteredSignals=="BUY"));
    end
end

if ~sentimentAvailable

    fprintf('Sentiment filter unavailable.\n');
    filteredSignals = arSignals;
    sentimentMean = NaN;
end

%% ============================================================
% 17. BUY & HOLD
% ============================================================

fprintf('\n-> Creating Buy & Hold benchmark...\n');

buyHoldSignals = repmat("BUY", numel(testIdx), 1);

%% ============================================================
% 18. RUN FINAL TEST BACKTESTS
% ============================================================

fprintf('\n============================================================\n');
fprintf(' FINAL TEST BACKTESTS\n');
fprintf('============================================================\n');

priceTest = prices(testIdx);
dateTest  = dates(testIdx);

initialCapital = 10000;
feeRate = 0.0010;

fprintf('Initial capital : $%.2f\n', initialCapital);
fprintf('Transaction cost: %.2f%%\n', feeRate*100);

fprintf('\n-> AR(5) strategy...\n');

arResult = runBacktest( ...
    priceTest, ...
    arSignals, ...
    initialCapital, ...
    feeRate, ...
    true);

fprintf('-> Sentiment-filtered AR(5)...\n');

sentimentResult = runBacktest( ...
    priceTest, ...
    filteredSignals, ...
    initialCapital, ...
    feeRate, ...
    true);

fprintf('-> Buy & Hold...\n');

buyHoldResult = runBacktest( ...
    priceTest, ...
    buyHoldSignals, ...
    initialCapital, ...
    0, ...
    false);

%% ============================================================
% 19. PERFORMANCE TABLE
% ============================================================

fprintf('\n============================================================\n');
fprintf(' TEST PERIOD PERFORMANCE\n');
fprintf('============================================================\n');

strategyNames = { ...
    'AR(5) Strategy'; ...
    'Sentiment-Filtered AR(5)'; ...
    'Buy & Hold'};

strategyResults = { ...
    arResult; ...
    sentimentResult; ...
    buyHoldResult};

numStrategies = numel(strategyNames);

FinalCapital = zeros(numStrategies,1);
TotalReturn = zeros(numStrategies,1);
AnnualizedReturn = zeros(numStrategies,1);
SharpeRatio = zeros(numStrategies,1);
SortinoRatio = zeros(numStrategies,1);
MaxDrawdown = zeros(numStrategies,1);
WinRate = zeros(numStrategies,1);
TradeCount = zeros(numStrategies,1);
ProfitFactor = zeros(numStrategies,1);

for i = 1:numStrategies

    r = strategyResults{i};

    FinalCapital(i) = r.finalCapital;
    TotalReturn(i) = r.totalReturnPct;
    AnnualizedReturn(i) = r.annualizedReturnPct;
    SharpeRatio(i) = r.sharpeRatio;
    SortinoRatio(i) = r.sortinoRatio;
    MaxDrawdown(i) = r.maxDrawdownPct;
    WinRate(i) = r.winRatePct;
    TradeCount(i) = r.tradeCount;
    ProfitFactor(i) = r.profitFactor;
end

comparisonTable = table( ...
    strategyNames, ...
    FinalCapital, ...
    TotalReturn, ...
    AnnualizedReturn, ...
    SharpeRatio, ...
    SortinoRatio, ...
    MaxDrawdown, ...
    WinRate, ...
    TradeCount, ...
    ProfitFactor, ...
    'VariableNames', { ...
    'Strategy', ...
    'FinalCapital', ...
    'TotalReturnPct', ...
    'AnnualizedReturnPct', ...
    'SharpeRatio', ...
    'SortinoRatio', ...
    'MaxDrawdownPct', ...
    'WinRatePct', ...
    'TradeCount', ...
    'ProfitFactor'});

disp(comparisonTable);

%% ============================================================
% 20. SAVE COMPARISON TABLE
% ============================================================

comparisonFile = fullfile( ...
    tablesDir, ...
    'backtest_comparison.csv');

writetable(comparisonTable, comparisonFile);

fprintf('\n-> Saved:\n');
fprintf('   %s\n', comparisonFile);

%% ============================================================
% 21. EQUITY CURVE
% ============================================================

fprintf('\n-> Generating equity curve...\n');

figure('Name', 'Trading Strategy Equity Curves', ...
    'Color', 'w');

plot( ...
    dateTest, ...
    arResult.equity, ...
    'LineWidth', 1.5);

hold on;

plot( ...
    dateTest, ...
    sentimentResult.equity, ...
    'LineWidth', 1.5);

plot( ...
    dateTest, ...
    buyHoldResult.equity, ...
    'LineWidth', 1.5);

grid on;

xlabel('Date');
ylabel('Portfolio Value ($)');

title('Test Period Equity Curves');

legend( ...
    'AR(5)', ...
    'Sentiment-Filtered AR(5)', ...
    'Buy & Hold', ...
    'Location', 'best');

hold off;

equityFigure = fullfile( ...
    figuresDir, ...
    'equity_curves.png');

saveas(gcf, equityFigure);
close(gcf);

fprintf('   Saved: %s\n', equityFigure);

%% ============================================================
% 22. DRAWDOWN PLOT
% ============================================================

fprintf('-> Generating drawdown plot...\n');

figure('Name', 'Trading Strategy Drawdowns', ...
    'Color', 'w');

plot( ...
    dateTest, ...
    100*arResult.drawdown, ...
    'LineWidth', 1.5);

hold on;

plot( ...
    dateTest, ...
    100*sentimentResult.drawdown, ...
    'LineWidth', 1.5);

plot( ...
    dateTest, ...
    100*buyHoldResult.drawdown, ...
    'LineWidth', 1.5);

grid on;

xlabel('Date');
ylabel('Drawdown (%)');

title('Test Period Drawdowns');

legend( ...
    'AR(5)', ...
    'Sentiment-Filtered AR(5)', ...
    'Buy & Hold', ...
    'Location', 'best');

hold off;

drawdownFigure = fullfile( ...
    figuresDir, ...
    'drawdowns.png');

saveas(gcf, drawdownFigure);
close(gcf);

fprintf('   Saved: %s\n', drawdownFigure);

%% ============================================================
% 23. SIGNAL OVERLAY
% ============================================================

fprintf('-> Generating trading signal plot...\n');

figure('Name', 'AR5 Trading Signals', ...
    'Color', 'w');

plot( ...
    dateTest, ...
    priceTest, ...
    'LineWidth', 1.2);

hold on;

buyMask = arSignals == "BUY";
sellMask = arSignals == "SELL";

if any(buyMask)

    plot( ...
        dateTest(buyMask), ...
        priceTest(buyMask), ...
        '^', ...
        'MarkerSize', 5);
end

if any(sellMask)

    plot( ...
        dateTest(sellMask), ...
        priceTest(sellMask), ...
        'v', ...
        'MarkerSize', 5);
end

grid on;

xlabel('Date');
ylabel('BTC Price ($)');

title('AR(5) Trading Signals');

if any(buyMask) && any(sellMask)

    legend( ...
        'BTC Price', ...
        'BUY', ...
        'SELL', ...
        'Location', 'best');

elseif any(buyMask)

    legend( ...
        'BTC Price', ...
        'BUY', ...
        'Location', 'best');

elseif any(sellMask)

    legend( ...
        'BTC Price', ...
        'SELL', ...
        'Location', 'best');

else

    legend('BTC Price', ...
        'Location', 'best');
end

hold off;

signalFigure = fullfile( ...
    figuresDir, ...
    'signals_overlay.png');

saveas(gcf, signalFigure);
close(gcf);

fprintf('   Saved: %s\n', signalFigure);

%% ============================================================
% 24. SAVE COMPLETE RESULTS
% ============================================================

fprintf('\n-> Saving complete backtest results...\n');

backtestFile = fullfile( ...
    modelsDir, ...
    'backtest_results.mat');

selectedModelName = 'AR(5)';

save( ...
    backtestFile, ...
    'arResult', ...
    'sentimentResult', ...
    'buyHoldResult', ...
    'comparisonTable', ...
    'valPred', ...
    'testPred', ...
    'arSignals', ...
    'filteredSignals', ...
    'buyHoldSignals', ...
    'bestThreshold', ...
    'bestValSharpe', ...
    'sentimentMean', ...
    'selectedModelName', ...
    'valRMSE', ...
    'valMAE', ...
    'valR2', ...
    'testRMSE', ...
    'testMAE', ...
    'testR2');

fprintf('   Saved:\n');
fprintf('   %s\n', backtestFile);

%% ============================================================
% 25. FINAL SUMMARY
% ============================================================

fprintf('\n============================================================\n');
fprintf(' [STEP 5 COMPLETE]\n');
fprintf('============================================================\n');

fprintf('Selected model       : AR(5)\n');
fprintf('Validation RMSE      : %.6f\n', valRMSE);
fprintf('Test RMSE            : %.6f\n', testRMSE);
fprintf('Trading threshold    : %.4f\n', bestThreshold);

fprintf('\nAR(5) Strategy:\n');
fprintf('  Final capital      : $%.2f\n', arResult.finalCapital);
fprintf('  Total return       : %.2f%%\n', arResult.totalReturnPct);
fprintf('  Sharpe ratio       : %.4f\n', arResult.sharpeRatio);
fprintf('  Max drawdown       : %.2f%%\n', arResult.maxDrawdownPct);
fprintf('  Trades             : %d\n', arResult.tradeCount);

fprintf('\nSentiment-Filtered AR(5):\n');
fprintf('  Final capital      : $%.2f\n', sentimentResult.finalCapital);
fprintf('  Total return       : %.2f%%\n', sentimentResult.totalReturnPct);
fprintf('  Sharpe ratio       : %.4f\n', sentimentResult.sharpeRatio);
fprintf('  Max drawdown       : %.2f%%\n', sentimentResult.maxDrawdownPct);
fprintf('  Trades             : %d\n', sentimentResult.tradeCount);

fprintf('\nBuy & Hold:\n');
fprintf('  Final capital      : $%.2f\n', buyHoldResult.finalCapital);
fprintf('  Total return       : %.2f%%\n', buyHoldResult.totalReturnPct);
fprintf('  Sharpe ratio       : %.4f\n', buyHoldResult.sharpeRatio);
fprintf('  Max drawdown       : %.2f%%\n', buyHoldResult.maxDrawdownPct);

fprintf('\nSaved files:\n');
fprintf('  %s\n', comparisonFile);
fprintf('  %s\n', backtestFile);
fprintf('  %s\n', equityFigure);
fprintf('  %s\n', drawdownFigure);
fprintf('  %s\n', signalFigure);

fprintf('\nProceeding to Step 6...\n\n');

end


%% ============================================================
% FIND COLUMN
% ============================================================

function columnName = findColumn(T, candidates)

columnName = '';

names = T.Properties.VariableNames;

for i = 1:numel(candidates)

    idx = strcmpi(names, candidates{i});

    if any(idx)

        columnName = names{find(idx,1)};
        return;

    end
end

% Fuzzy search
for i = 1:numel(candidates)

    idx = contains( ...
        lower(names), ...
        lower(candidates{i}));

    if any(idx)

        columnName = names{find(idx,1)};
        return;

    end
end

end


%% ============================================================
% CONVERT TO NUMERIC
% ============================================================

function x = convertToNumeric(x)

if isnumeric(x)

    x = double(x(:));
    return;

end

if iscell(x)

    x = string(x);

end

if isstring(x) || ischar(x) || iscategorical(x)

    x = str2double(string(x));
    x = x(:);
    return;

end

error('step5:conversionError', ...
    'Could not convert variable to numeric.');

end


%% ============================================================
% CONVERT TO DATETIME
% ============================================================

function d = convertToDatetime(x)

if isdatetime(x)

    d = x(:);
    return;

end

if isnumeric(x)

    x = x(:);

    % MATLAB datenum detection
    if median(x, 'omitnan') > 100000

        d = datetime(x, ...
            'ConvertFrom', 'datenum');

    else

        d = datetime(x, ...
            'ConvertFrom', 'posixtime');

    end

    return;

end

if iscell(x)

    x = string(x);

end

if isstring(x) || ischar(x) || iscategorical(x)

    s = string(x);

    d = NaT(size(s));

    % Try automatic parsing first
    try

        d = datetime(s);

    catch

        formats = { ...
            'yyyy-MM-dd', ...
            'yyyy-MM-dd HH:mm:ss', ...
            'dd-MM-yyyy', ...
            'MM/dd/yyyy', ...
            'yyyy/MM/dd'};

        for i = 1:numel(formats)

            try

                temp = datetime( ...
                    s, ...
                    'InputFormat', formats{i});

                good = ~isnat(temp);

                d(good) = temp(good);

                if all(~isnat(d))
                    break;
                end

            catch
            end
        end
    end

    d = d(:);
    return;

end

error('step5:dateConversionError', ...
    'Could not convert date column to datetime.');

end


%% ============================================================
% FIT AR MODEL
% ============================================================

function model = fitARModel(y, lagOrder)

y = y(:);

n = numel(y);

if n <= lagOrder

    error('step5:arDataError', ...
        'Not enough observations for AR(%d).', ...
        lagOrder);
end

rows = n - lagOrder;

X = zeros(rows, lagOrder+1);
Y = zeros(rows,1);

for t = lagOrder+1:n

    row = t-lagOrder;

    lagValues = y(t-lagOrder:t-1);

    lagValues = flipud(lagValues);

    X(row,:) = [1; lagValues]';

    Y(row) = y(t);
end

beta = pinv(X)*Y;

model.beta = beta;
model.lagOrder = lagOrder;

end


%% ============================================================
% GENERATE SIGNALS
% ============================================================

function signals = generateSignals( ...
    predictions, ...
    buyThreshold, ...
    sellThreshold)

predictions = predictions(:);

signals = repmat("HOLD", ...
    numel(predictions),1);

signals(predictions > buyThreshold) = "BUY";

signals(predictions < -sellThreshold) = "SELL";

end


%% ============================================================
% BACKTEST
% ============================================================

function result = runBacktest( ...
    prices, ...
    signals, ...
    initialCapital, ...
    feeRate, ...
    allowShort)

prices = prices(:);
signals = string(signals(:));

n = numel(prices);

if n < 2

    error('step5:backtestDataError', ...
        'At least two prices are required.');

end

if numel(signals) ~= n

    error('step5:backtestLengthError', ...
        'Price and signal lengths do not match.');

end

equity = zeros(n,1);
equity(1) = initialCapital;

positions = zeros(n,1);

dailyReturns = zeros(n-1,1);

capital = initialCapital;

currentPosition = 0;
tradeCount = 0;

for t = 1:n-1

    signal = signals(t);

    % ---------------------------------------------------------
    % TARGET POSITION
    % ---------------------------------------------------------

    if signal == "BUY"

        targetPosition = 1;

    elseif signal == "SELL" && allowShort

        targetPosition = -1;

    else

        targetPosition = 0;

    end

    % ---------------------------------------------------------
    % TRANSACTION COST
    % ---------------------------------------------------------

    positionChange = abs( ...
        targetPosition-currentPosition);

    if positionChange > 0

        transactionCost = ...
            capital * feeRate * positionChange;

        capital = capital - transactionCost;

        tradeCount = tradeCount+1;

    end

    currentPosition = targetPosition;

    positions(t) = currentPosition;

    % ---------------------------------------------------------
    % NEXT-DAY MARKET RETURN
    % ---------------------------------------------------------

    marketReturn = ...
        (prices(t+1)-prices(t))/prices(t);

    strategyReturn = ...
        currentPosition*marketReturn;

    dailyReturns(t) = strategyReturn;

    capital = ...
        capital*(1+strategyReturn);

    equity(t+1) = capital;

end

positions(end) = currentPosition;

% -------------------------------------------------------------
% RETURNS
% -------------------------------------------------------------

totalReturnPct = ...
    100*(capital/initialCapital-1);

numDays = numel(dailyReturns);

annualizedReturnPct = ...
    100*((capital/initialCapital)^(365/max(numDays,1))-1);

% -------------------------------------------------------------
% SHARPE
% -------------------------------------------------------------

dailyStd = std(dailyReturns);

if dailyStd > eps

    sharpeRatio = ...
        mean(dailyReturns)/dailyStd*sqrt(365);

else

    sharpeRatio = 0;

end

% -------------------------------------------------------------
% SORTINO
% -------------------------------------------------------------

downside = dailyReturns(dailyReturns < 0);

if isempty(downside)

    sortinoRatio = 0;

else

    downsideStd = sqrt(mean(downside.^2));

    if downsideStd > eps

        sortinoRatio = ...
            mean(dailyReturns)/downsideStd*sqrt(365);

    else

        sortinoRatio = 0;

    end
end

% -------------------------------------------------------------
% DRAWDOWN
% -------------------------------------------------------------

runningMax = cummax(equity);

drawdown = ...
    (equity-runningMax)./max(runningMax,eps);

maxDrawdownPct = ...
    100*min(drawdown);

% -------------------------------------------------------------
% WIN RATE
% -------------------------------------------------------------

positive = sum(dailyReturns > 0);
negative = sum(dailyReturns < 0);

active = positive+negative;

if active > 0

    winRatePct = ...
        100*positive/active;

else

    winRatePct = 0;

end

% -------------------------------------------------------------
% PROFIT FACTOR
% -------------------------------------------------------------

grossProfit = ...
    sum(dailyReturns(dailyReturns > 0));

grossLoss = ...
    abs(sum(dailyReturns(dailyReturns < 0)));

if grossLoss > eps

    profitFactor = ...
        grossProfit/grossLoss;

else

    profitFactor = Inf;

end

% -------------------------------------------------------------
% OUTPUT
% -------------------------------------------------------------

result = struct();

result.equity = equity;
result.dailyReturn = dailyReturns;
result.drawdown = drawdown;
result.positions = positions;

result.initialCapital = initialCapital;
result.finalCapital = capital;

result.totalReturnPct = totalReturnPct;
result.annualizedReturnPct = annualizedReturnPct;

result.sharpeRatio = sharpeRatio;
result.sortinoRatio = sortinoRatio;

result.maxDrawdownPct = maxDrawdownPct;

result.winRatePct = winRatePct;
result.profitFactor = profitFactor;

result.tradeCount = tradeCount;

end